
name: 'Setup infra'

on:
  push:
    branches:
      - master
    paths:
      - "terraform/**" # terraform 하위 경로에 변화가 있을떄 동작하게 한다.
  workflow_dispatch: # 원할때 실할 할 수 있는 버튼을 github action에 만들기

jobs:
  terraform-run:
    runs-on: ubuntu-latest
    steps:
      - name: checkout Repository
        uses: actions/checkout@v4
        
      - name: Aws Configure # aws 인증정보 제공
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2  
      - name: Setup Terraform # 테라폼 설치
        uses: hashicorp/setup-terraform@v4

      - name: Terraform Init & Apply # ./terraform 안에 있는 terraform 자원을 init, apply 한번에
        run: |
          terraform init
          terraform apply --auto-approve
         # ./terraform 폴더안에서 위의 명령어가 실행 됨 
        working-directory: ./terraform

